Added some text to the homepage
nark-app/nark-app.github.io pull request #14
Opened 2021-04-16 03:48 UTC by NickSheetz

2021-04-16 11:26 UTC, Aaron-Rumpler requested changes

2021-04-16 11:26 UTC, Aaron-Rumpler commented on index.md
> +## Homepage
Leave these at a single `#`. The title's separate, so these are the top level headings for the page. The site makes it look a bit funny at the moment, but that'll be fixed on Saturday (so probably fixed by the time you read this).

2021-04-16 11:26 UTC, Aaron-Rumpler commented on index.md
> +We are four computer science student from the University of Otago - Nick Sheetz, Aaron Rumpler, Reuben Sweetman, Khrys Samsonova. We are completing our 3rd year and developing this app for our COSC34
That's 'student**s**', not 'student'. Also, it should probably be:
> Nick Sheetz, Aaron Rumpler, Reuben Sweetman, **and** Khrys Samsonova.

2021-04-18 04:02 UTC, bstabs-alt approved these changes

2021-04-18 04:03 UTC, bstabs-alt approved these changes

2021-04-18 04:35 UTC, closed without merging