Update research.md
nark-app/nark-app.github.io pull request #5
Opened 2021-04-14 01:00 UTC by bstabs-alt

2021-04-14 01:18 UTC, Aaron-Rumpler requested changes

2021-04-14 01:18 UTC, Aaron-Rumpler commented on research.md
> +</table>
Do we really want a table here. Also, you can do tables in Markdown, no need for HTML.

2021-04-14 01:18 UTC, Aaron-Rumpler commented on research.md
>  </div>
Do we really need to justify the text. Most stuff's just left-aligned and looks fine.

2021-04-14 01:30 UTC, NickSheetz approved these changes

2021-04-14 01:51 UTC, Khrys-Samsonova submitted a review, later dismissed

2021-04-15 00:51 UTC, Khrys-Samsonova approved these changes

2021-04-15 00:52 UTC, Aaron-Rumpler commented on research.md
> +> - This category has several different approaches used by these apps such as blocking websites, giving external motivation for working, and suggesting whether a user really wants to procrastinate.
Not sure why the bullet points are quoted?

2021-04-15 00:53 UTC, Aaron-Rumpler commented on research.md
> +<h1 align="center">What already exists that is similar to our idea?</h1>
My recommendation is to not worry much about the formatting, the static site generator will deal with that when it converts it to HTML.

2021-04-15 01:11 UTC, Aaron-Rumpler commented on research.md
> +<h1 align="center">What already exists that is similar to our idea?</h1>
If we want to justify or center text, we'd be better off doing it in the site template.

2021-04-15 01:12 UTC, Aaron-Rumpler commented on research.md
> +<h1 align="center">What already exists that is similar to our idea?</h1>
I'd suggest doing something like #9.

2021-04-15 22:20 UTC, Aaron-Rumpler approved these changes

2021-04-15 22:22 UTC, Khrys-Samsonova approved these changes

2021-04-15 22:46 UTC, NickSheetz approved these changes

2021-04-15 22:57 UTC, merged