clarified market
nark-app/nark-app.github.io pull request #7
Opened 2021-04-14 01:31 UTC by Khrys-Samsonova

Added more paragraphs

2021-04-14 01:31 UTC, NickSheetz submitted a review, later dismissed

2021-04-14 01:34 UTC, bstabs-alt submitted a review, later dismissed
nice

2021-04-14 01:35 UTC, Aaron-Rumpler requested changes

2021-04-14 01:35 UTC, Aaron-Rumpler commented on market.md
> -- Maybe a way to track how student are going
Maybe is the correct spelling.

2021-04-14 01:35 UTC, Aaron-Rumpler commented on market.md
> +With some anonymous data collection we could allow the university staff to see some statistics on where and when students are on campus. This could allow for some improvements to be made by the unive
The university probably already has decent data on this from the WiFi.

2021-04-14 01:35 UTC, Aaron-Rumpler commented on market.md
> -- Maybe a way to track how student are going
?

2021-04-14 01:50 UTC, Aaron-Rumpler requested changes

2021-04-14 01:50 UTC, Aaron-Rumpler commented on market.md
> +- Maybe a way to track how students are going
What do you mean by this? Welfare checks?

2021-04-15 00:22 UTC, bstabs-alt approved these changes
groovy

2021-04-15 00:25 UTC, NickSheetz commented on market.md
> +With some anonymous data collection we could allow the university staff to see some statistics on where and when students are on campus. This could allow for some improvements to be made by the unive
Whether we implement it or not isn't the point. Good to show we are thinking about all the possible implementations this app could have.

2021-04-15 00:27 UTC, Khrys-Samsonova commented on market.md
> +- Maybe a way to track how students are going
No. More so what I was talking about above with tracking usage of university locations.

2021-04-15 00:29 UTC, Aaron-Rumpler commented on market.md
> +- Maybe a way to track how students are going
OK, so that might need to be clarified a bit.

2021-04-15 00:31 UTC, Khrys-Samsonova commented on market.md
> +- Maybe a way to track how students are going
the whole point of the bullet points is to be a shorter version of what I stated above. so it already clarified...

2021-04-15 00:31 UTC, Aaron-Rumpler commented on market.md
> +With some anonymous data collection we could allow the university staff to see some statistics on where and when students are on campus. This could allow for some improvements to be made by the unive
Maybe something like 
> With some opt-in anonymous data collection we could potentially provide the University staff with additional statistics on where and when students are on campus.

2021-04-15 00:36 UTC, Aaron-Rumpler commented on market.md
> +- Maybe a way to track how students are going
It doesn't read that way to me. What does everyone else think?

2021-04-15 00:41 UTC, Khrys-Samsonova commented on market.md
> +With some anonymous data collection we could allow the university staff to see some statistics on where and when students are on campus. This could allow for some improvements to be made by the unive
yeah I'm happy with that if everyone else is

2021-04-15 00:45 UTC, Khrys-Samsonova commented on market.md
> +- Maybe a way to track how students are going
Could change it to "Maybe a way to track saturation of students at different locations around campus"

2021-04-15 00:45 UTC, Aaron-Rumpler commented on market.md
> +- Maybe a way to track how students are going
That sounds much better.

2021-04-15 00:48 UTC, Aaron-Rumpler approved these changes

2021-04-15 00:49 UTC, Aaron-Rumpler approved these changes

2021-04-15 00:59 UTC, bstabs-alt approved these changes
good work

2021-04-15 21:07 UTC, merged